yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("create/", views.post_create, name="post_create"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("", views.index, name="index"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path(
        "posts/<int:post_id>/comment/", views.add_comment, name="add_comment"
    ),
    path("follow", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permisson_denied"

urlpatterns = [
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="index")),
    path("about/", include("about.urls", namespace="about")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    slug = models.SlugField(max_length=200, unique=True, verbose_name="ЧПУ")
    description = models.TextField(max_length=400, verbose_name="Описание")

    class Meta:
        verbose_name_plural = "Группы"
        verbose_name = "Группу"

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        max_length=400,
        help_text="Введите текст поста",
        verbose_name="Текст поста",
    )
    pub_date = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата публикации"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор",
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="posts",
        verbose_name="Группа",
        help_text="Выберите группу",
    )
    image = models.ImageField("Картинка", upload_to="posts/", blank=True)

    class Meta:
        ordering = ["-pub_date"]
        verbose_name_plural = "Посты"
        verbose_name = "Пост"

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="comments"
    )
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="follower"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="following"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"], name="unique_follower_following"
            )
        ]

    def __str__(self):
        return f"{self.user.username} подписан на {self.author.username}"

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["text", "group", "image"]
        help_texts = {
            "text": "Текст нового поста",
            "group": "Группа, к которой будет относиться пост",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from .utils import paginate_page
from .forms import PostForm, CommentForm
from .models import Group, Post, Follow

User = get_user_model()


def index(request):
    post_list = Post.objects.select_related("group", "author")
    page_obj = paginate_page(request, post_list)
    context = {"page_obj": page_obj}
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related("group")
    page_obj = paginate_page(request, posts)
    context = {"group": group, "page_obj": page_obj}
    return render(request, "posts/group_list.html", context)


def profile(request, username):
    author_profile = get_object_or_404(User, username=username)
    post_list = author_profile.posts.all()
    page_obj = paginate_page(request, post_list)
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(
            author=author_profile, user=request.user
        ).exists()
    )
    context = {
        "page_obj": page_obj,
        "author": author_profile,
        "following": following,
    }
    return render(request, "posts/profile.html", context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm()
    comments_for_post = post.comments.all()
    context = {"post": post, "form": form, "comments": comments_for_post}
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        create_post = form.save(commit=False)
        create_post.author = request.user
        create_post.save()
        return redirect("posts:profile", create_post.author)
    context = {"form": form}
    return render(request, "posts/create_post.html", context)


@login_required
def post_edit(request, post_id):
    edit_post = get_object_or_404(Post, id=post_id)
    if request.user != edit_post.author:
        return redirect("posts:post_detail", post_id)
    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=edit_post
    )
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id)
    context = {"form": form, "is_edit": True}
    return render(request, "posts/create_post.html", context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(
        author__following__user=request.user
    ).select_related("group")
    page_obj = paginate_page(request, post_list)
    context = {"page_obj": page_obj}
    return render(request, "posts/follow.html", context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect("posts:profile", username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}Новый пост{% endblock %}
{% block content %}
<div class="row justify-content-center">
<div class="col-md-8 p-5">
  <div class="card">
    <div class="card-header">{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}</div>
    <div class="card-body">
        {% include 'includes/form.html' %}
        <div class="d-flex justify-content-end">
          <button type="submit" class="btn btn-primary">{% if is_edit %}Сохранить{% else %}Добавить{% endif %}</button>
        </div>
      </form>
    </div>
  </div>
</div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Мои подписки{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% for post in page_obj %}
  <ul>
    <li>
      {% include 'posts/includes/author.html' %}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:'d E Y' }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text | linebreaksbr }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<div class="d-flex justify-content-center">
  <div>
    {% include 'includes/paginator.html' %}
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Записи сообщества: {{ group.title }}{% endblock %}
{% block content %}
<h1>{{ group.title }}</h1>
<p>{{ group.description|linebreaks }}</p>
{% for post in page_obj %}
<ul>
  <li>
    {% include 'posts/includes/author.html' %}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:'d E Y' }}
  </li>
</ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {{ post.text|linebreaks }}
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<div class="d-flex justify-content-center">
  <div>{% include 'includes/paginator.html' %}</div>
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load cache %}
{% cache 20 index_page %}
{% include 'posts/includes/switcher.html' %}
{% for post in page_obj %}
  <ul>
    <li>
      {% include 'posts/includes/author.html' %}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:'d E Y' }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text|linebreaksbr }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<div class="d-flex justify-content-center">
  <div>
    {% include 'includes/paginator.html' %}
  </div>
  {% endcache %}
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}Пост {{ post|truncatechars:30 }}{% endblock %}
{% load thumbnail %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:'d E Y' }}
      </li>
      <li class="list-group-item">
        Группа:
        {% if post.group %}
        {{ post.group.title }}
        {% else %}
        ---Пусто---
        {% endif %}
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
      </li>
      <li class="list-group-item">
        {% include 'posts/includes/author.html' %}
      </li>
      <li class="list-group-item">
        Всего постов автора: {{ post.author.posts.count }}
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text | linebreaksbr }}</p>
  {% if request.user == post.author %}
    <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">редактировать запись</a>
  {% endif %}
  </article>
  {% include 'includes/comments.html' %}
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    {% if author.get_full_name %}
        {{ author.get_full_name }}
    {% else %}
        {{ author }}
    {% endif %} профайл пользователя
{% endblock %}
{% block content %}
<div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
     {% endif %}
  </div>
{% for post in page_obj %}
    <ul>
        <li>
        Дата публикации: {{ post.pub_date|date:'d E Y' }}
        </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text | linebreaksbr }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    <br>
    {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<div class="d-flex justify-content-center">
    <div>{% include 'includes/paginator.html' %}</div>
</div>
{% endblock %}